{% set version = '0.4.1.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mockery
  version: {{ version|replace("-", "_") }}

source:
  fn: mockery_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/mockery_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mockery/mockery_{{ version }}.tar.gz
  sha256: cb5025f09f96d024eb4d6c335f26d1d538b0cd8aee56488c2f5b702f2593d5ed

build:
  merge_build_host: True  # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-testthat

  run:
    - r-base
    - r-testthat

test:
  commands:
    - $R -e "library('mockery')"           # [not win]
    - "\"%R%\" -e \"library('mockery')\""  # [win]

about:
  home: https://github.com/n-s-f/mockery
  license: MIT
  summary: 'The two main functionalities of this package are creating mock objects (functions)
    and selectively intercepting calls to a given function that originate in some other
    function. It can be used with any testing framework available for R. Mock objects
    can be injected with either this package''s own stub() function or a similar with_mock()
    facility present in the testthat package.'
  license_family: MIT
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\MIT'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
