# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fgNJ+J/17tpP9ObL+cWNo7x7lsNvzujQCOk/GfwTX8mOOWCZtY3hwxpH0yvm026iojz5n+F96M2PUgNyFoTxbc3rP1OyqKOpBZQIm2QvzV/zcPg1vvShr4OapQ5wc0/afrmvDKtkGUevg+h8LwQDqzcG3x+uWq0XZH9N6XHkGvb2DaGEcupxi1BjTgwUUWWdT+kGc2OxqvxtA0b/cIpxQc3ZwX7fRkXCXhblgNCggXAf1pV61X5kvWBrDauPbBvMog+n294SQFT7o6f8YCy4rMa6CcRL4MCi/lv5dzQw225QXd6VGTmlEj+fZz2UJ+FWvKFgmL+tob/fwM6A9ohvwdAnjj826Ui6R0NGs3uueDqLnw9XiapvEANO5UhyRkNxDo+aGqEuDHF+HO53s3dTcLj6Rvq1sKgOOc5vqHO3auzZkQ1IhU1iF+JU++dbIewy/yzg8cLJEOJgtRPwR8fGEclT2pXgeWlLPFOTU4pcnyEXNiwCViJ1thy5bVsLBLL/SOqtfz4DWUBO+GZQCp4WtXMjCxgI3II21WKjkkTWA+GxnQR9Q/f/VnRVkVtjNSxot1Qgy0CwCr0xIeOjZRMCIk6O7bddQoNvfnzBjD2AzZI8cEbtDc2BAUg2Bxy0mcepdiN64TmFTiU8fwq+2VUkf3UZtvJKDLaonAz16P9qRB0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
