travis:
  secure:
    BINSTAR_TOKEN: d0O2PFZlSH/SEy/v/P8itlDzgAD3yreZuC3W4Q0b4QYZUzdA4Fmd+700vBi1FDQeW4kzkwLv4jqeYkFCzqPgpit6RpVzjWSRcxQ2riftRdLr5EOT958tyCIMFCELcUOeM9uFrxS/MFwq0NqObKqrRqoZodEcT2WqkacxE6kdGOk8bQ1Uix5CRv+liGMs3Spimw17shnIeoqVYiRjR5rzAajjsvGcxEr/e7CLqXIZzbj3Csp3tsYkE4vrXVjIch7XcQlzLojoWy5ZQ5nfTW2tDnZYZWY8/bsSBno/3pUWcEvmZVVhcoLRDNWvcpCJ1ZjiXqiIxCVDvCFyUtUELg/AiTNcfa0+yWQuUS+NXMOsg0IlRNY0dQZ2vjAt8XYthtQgitslOC6y8eQYpEJ3roC9ONxz1e7xRh06b6KL/M9Q12qJAKrw/Pi6iDza6uQBv8vdE6otOGr80oJQbDeoQsnr5EXsowvnn2okO5sNbwfGi6jDvjA5ILKbRzqb643dO7Etkb8aGKS7Te3cbDPO9+J3Ui5fe1axA5+Xb09P9OtmSXf/UJJe3zqwRQrj6xs/jrZVyBoR/jBgC4KZ4BOd9RPN5qiTiBCzy8d3fQuT9TLiXLlL2Qdd2aiYQi1gosnqjHY6Z9pM06oTbekjOt9TOqI4SA7rPV1rLu/5bdKOgyi17Ek=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
