appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: fgNJ+J/17tpP9ObL+cWNo7x7lsNvzujQCOk/GfwTX8mOOWCZtY3hwxpH0yvm026iojz5n+F96M2PUgNyFoTxbc3rP1OyqKOpBZQIm2QvzV/zcPg1vvShr4OapQ5wc0/afrmvDKtkGUevg+h8LwQDqzcG3x+uWq0XZH9N6XHkGvb2DaGEcupxi1BjTgwUUWWdT+kGc2OxqvxtA0b/cIpxQc3ZwX7fRkXCXhblgNCggXAf1pV61X5kvWBrDauPbBvMog+n294SQFT7o6f8YCy4rMa6CcRL4MCi/lv5dzQw225QXd6VGTmlEj+fZz2UJ+FWvKFgmL+tob/fwM6A9ohvwdAnjj826Ui6R0NGs3uueDqLnw9XiapvEANO5UhyRkNxDo+aGqEuDHF+HO53s3dTcLj6Rvq1sKgOOc5vqHO3auzZkQ1IhU1iF+JU++dbIewy/yzg8cLJEOJgtRPwR8fGEclT2pXgeWlLPFOTU4pcnyEXNiwCViJ1thy5bVsLBLL/SOqtfz4DWUBO+GZQCp4WtXMjCxgI3II21WKjkkTWA+GxnQR9Q/f/VnRVkVtjNSxot1Qgy0CwCr0xIeOjZRMCIk6O7bddQoNvfnzBjD2AzZI8cEbtDc2BAUg2Bxy0mcepdiN64TmFTiU8fwq+2VUkf3UZtvJKDLaonAz16P9qRB0=}
